title = "Studentenes bridgeklubb"
baseURL = "https://www.studentenesbk.no/"
languageCode = "nb-no"
DefaultContentLanguage = "nb-no"
enableEmoji = true

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
    kurs = "/:filename/"

[menu]
    [[menu.main]]
        name = "Heim"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Kurs"
        url = "/kurs/"
        weight = 3
    [[menu.main]]
        name = "Trondheim Cup"
        url = "/trondheimcup/"
        weight = 4
    [[menu.main]]
        name = "Hva er bridge?"
        pre = "book-open"
        url = "/hva-er-bridge/"
        weight = 5
    [[menu.main]]
        name = "Om"
        pre = "book"
        url = "/om/"
        weight = 10

[params]
  description = ""
  facebook = "https://www.facebook.com/groups/291823804205035"
  featured_image = "/images/playing-cards-dark.jpg"
  custom_css = ["css/custom.css"]
  defaultKeywords = "studentenes bridgeklubb,studbk,studentenesbk,bridge,Trondheim,bridgekurs"
