title = "Studentenes bridgeklubb"
baseURL = "https://example.com"
languageCode = "nb-no"
enableEmoji = true

[permalinks]
    kurs = "/:filename/"

[menu]
    [[menu.main]]
        name = "Heim"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Kurs"
        url = "/kurs/"
        weight = 2
    [[menu.main]]
        name = "Hva er bridge?"
        pre = "book-open"
        url = "/hva-er-bridge/"
        weight = 3
    [[menu.main]]
        name = "Om"
        pre = "book"
        url = "/om/"
        weight = 4

[params]
  description = ""
  facebook = "https://www.facebook.com/groups/291823804205035"
  featured_image = "/images/playing-cards-dark.jpg"
  custom_css = ["css/custom.css"]
