backend:
    name: git-gateway
    branch: master

media_folder: "static/images/uploads" 
public_folder: "/images/uploads" 

collections:
  - name: "trondheimcup"
    label: "Trondheim Cup - resultater"
    files:
      - label: "Resultater"
        name: "resultater"
        file: "data/trondheimcup.json"
        fields:
          - label: "Resultat"
            name: "resultat"
            widget: "list"
            fields:
              - {label: "Navn", name: "title", widget: "string"}
              - {label: "Dato", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: false}
              - {label: "Link", name: "url", widget: "string"}
              - {label: "Par/lag", name: "type", widget: "select", options: ["pairs", "teams", "single"], default: ["pairs"]}
